// 낱말 데이터. 그림은 이모지를 사용해 추가 파일 없이 오프라인에서도 보이게 했습니다.
// sound: 카드를 누르면 낱말 다음에 읽어 주는 의성어 (없으면 생략)
export const CATEGORIES = [
  {
    id: 'animals', name: '동물', icon: '🐶', color: '#FFD8A8',
    words: [
      { word: '강아지', emoji: '🐶', sound: '멍멍' },
      { word: '고양이', emoji: '🐱', sound: '야옹' },
      { word: '소', emoji: '🐮', sound: '음매' },
      { word: '돼지', emoji: '🐷', sound: '꿀꿀' },
      { word: '닭', emoji: '🐔', sound: '꼬끼오' },
      { word: '오리', emoji: '🦆', sound: '꽥꽥' },
      { word: '양', emoji: '🐑', sound: '메에' },
      { word: '말', emoji: '🐴', sound: '히힝' },
      { word: '사자', emoji: '🦁', sound: '어흥' },
      { word: '코끼리', emoji: '🐘', sound: '뿌우' },
      { word: '토끼', emoji: '🐰', sound: '깡총깡총' },
      { word: '개구리', emoji: '🐸', sound: '개굴개굴' },
      { word: '물고기', emoji: '🐟', sound: '뻐끔뻐끔' },
      { word: '새', emoji: '🐦', sound: '짹짹' },
    ],
  },
  {
    id: 'fruits', name: '과일', icon: '🍎', color: '#FFC9C9',
    words: [
      { word: '사과', emoji: '🍎' },
      { word: '바나나', emoji: '🍌' },
      { word: '딸기', emoji: '🍓' },
      { word: '포도', emoji: '🍇' },
      { word: '수박', emoji: '🍉' },
      { word: '귤', emoji: '🍊' },
      { word: '복숭아', emoji: '🍑' },
      { word: '배', emoji: '🍐' },
    ],
  },
  {
    id: 'food', name: '먹을 것', icon: '🍚', color: '#FFEC99',
    words: [
      { word: '밥', emoji: '🍚', sound: '냠냠' },
      { word: '우유', emoji: '🥛', sound: '꿀꺽꿀꺽' },
      { word: '물', emoji: '💧', sound: '꿀꺽' },
      { word: '빵', emoji: '🍞', sound: '냠냠' },
      { word: '달걀', emoji: '🥚' },
      { word: '과자', emoji: '🍪', sound: '바삭바삭' },
      { word: '치즈', emoji: '🧀' },
      { word: '당근', emoji: '🥕', sound: '아삭아삭' },
    ],
  },
  {
    id: 'vehicles', name: '탈것', icon: '🚗', color: '#A5D8FF',
    words: [
      { word: '자동차', emoji: '🚗', sound: '부릉부릉' },
      { word: '버스', emoji: '🚌', sound: '빵빵' },
      { word: '기차', emoji: '🚂', sound: '칙칙폭폭' },
      { word: '비행기', emoji: '✈️', sound: '슈웅' },
      { word: '배', emoji: '⛵', sound: '둥실둥실' },
      { word: '자전거', emoji: '🚲', sound: '따르릉' },
      { word: '소방차', emoji: '🚒', sound: '삐뽀삐뽀' },
      { word: '구급차', emoji: '🚑', sound: '삐뽀삐뽀' },
    ],
  },
  {
    id: 'body', name: '몸', icon: '👀', color: '#D0BFFF',
    words: [
      { word: '눈', emoji: '👀', sound: '깜빡깜빡' },
      { word: '코', emoji: '👃', sound: '킁킁' },
      { word: '입', emoji: '👄', sound: '아' },
      { word: '귀', emoji: '👂' },
      { word: '손', emoji: '✋', sound: '짝짝짝' },
      { word: '발', emoji: '🦶', sound: '콩콩' },
    ],
  },
  {
    id: 'things', name: '물건', icon: '⚽', color: '#B2F2BB',
    words: [
      { word: '공', emoji: '⚽', sound: '데굴데굴' },
      { word: '신발', emoji: '👟' },
      { word: '모자', emoji: '🧢' },
      { word: '책', emoji: '📖' },
      { word: '컵', emoji: '🥤' },
      { word: '숟가락', emoji: '🥄' },
      { word: '시계', emoji: '⏰', sound: '똑딱똑딱' },
      { word: '전화', emoji: '📱', sound: '여보세요' },
      { word: '곰인형', emoji: '🧸', sound: '꼬옥' },
    ],
  },
  {
    id: 'nature', name: '자연', icon: '🌞', color: '#C3FAE8',
    words: [
      { word: '해', emoji: '🌞', sound: '반짝반짝' },
      { word: '달', emoji: '🌙' },
      { word: '별', emoji: '⭐', sound: '반짝반짝' },
      { word: '꽃', emoji: '🌷', sound: '향기로워' },
      { word: '나무', emoji: '🌳' },
      { word: '비', emoji: '🌧️', sound: '주룩주룩' },
      { word: '눈사람', emoji: '⛄' },
    ],
  },
];
